[versions]
agp = "8.3.1"
androidUtils = "0.0.5"
annotation = "1.7.1"
appcompat = "1.6.1"
blurView = "version-2.0.3"
circleimageview = "3.1.0"
constraintlayout = "2.1.4"
coreSplashscreen = "1.0.1"
flexbox = "3.0.0"
glide = "4.16.0"
gson = "2.10.1"
hiddenapibypassVersion = "4.3"
libsuVersion = "5.2.2"
material = "1.11.0"
palette = "1.0.0"
preferenceKtx = "1.2.1"
recyclerview = "1.3.2"
recyclerviewSelection = "1.1.0"
remotepreferences = "0.8"
shizuku = "12.1.0"
workRuntime = "2.9.0"

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
agp-library = { id = "com.android.library", version.ref = "agp" }

[libraries]
androidUtils = { module = "me.jfenn:AndroidUtils", version.ref = "androidUtils" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
blurView = { module = "com.github.Dimezis:BlurView", version.ref = "blurView" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
libsu-core = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsuVersion" }
libsu-service = { module = "com.github.topjohnwu.libsu:service", version.ref = "libsuVersion" }
lsposed-hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypassVersion" }
material = { module = "com.google.android.material:material", version.ref = "material" }
palette = { module = "androidx.palette:palette", version.ref = "palette" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
recyclerview-selection = { module = "androidx.recyclerview:recyclerview-selection", version.ref = "recyclerviewSelection" }
remotepreferences = { module = "com.crossbowffs.remotepreferences:remotepreferences", version.ref = "remotepreferences" }
shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizuku" }
shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku" }
work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }